### ISSUE TITLE
Add 7z Support for Out Piping

### ISSUE THREAD

**Issue by joesixpack** [jinfeihan57/p7zip#103]
7z does not support -so but xz does, so the newer compression methods cannot be used for piping beyond -si.  When transfering hundreds of GB's to a remote server, there is no need for a [temporary] local file to be created.

**Comment by jinfeihan57** [comment]
what do you mean '7z does not support -so but xz does,'? According to https://github.com/jinfeihan57/p7zip/blob/master/DOC/MANUAL/7-zip.chm
the 7z support -so and -si.
![image](https://user-images.githubusercontent.com/38484902/100559345-40c19b00-32ed-11eb-886c-6020ba37dab8.png)

**Comment by joesixpack** [comment]
Try it, -so does not work with 7z format because of how 7z requires streaming support.  -so woth 7z results in error E_NOTIMPL.  -so only supports xz, gzip, bzip2 and tar.

**Comment by jinfeihan57** [comment]
Oh,I see what you mean.
BUT p7zip is a Linux version of 7zip. Therefore, its behavior is similar to 7zip. 
If 7zip is not supported, p7zip is not supported too. Sorry about that.
But  you can open issue at [7zip forum](https://sourceforge.net/p/sevenzip/discussion/45797/).

**Comment by TheOneRing** [comment]
We use -so for years and never head an issue https://invent.kde.org/packaging/craft/-/blob/master/bin/utils.py#L123
```
C:\CraftRoot\dev-utils\bin\7za.exe x C:\CraftRoot\download\archives\libs\libpng\libpng-1.6.37.tar.gz -so -bsp2 | C:\CraftRoot\dev-utils\bin\7za.exe x -si -oC:\CraftRoot\build\_\8777ed6f -ttar -bsp0
```

The same code is executed on linux:
```
/home/hannah/CraftRoot/bin/7za x /home/hannah/CraftRoot/download/archives/libs/libpng/libpng-1.6.37.tar.gz -so -bsp2 | /usr/bin/tar --directory /home/hannah/CraftRoot/build/libs/libpng/work -xf -
```

**Comment by jinfeihan57** [comment]
@TheOneRing

**Comment by jinfeihan57** [comment]
@TheOneRing  
 .7z format does not support -so  switch.
https://invent.kde.org/packaging/craft/-/blob/master/bin/utils.py#L133
If the -so switch is used with the command that creates archive, it works only with some archive formats: xz, gzip, bzip2 and tar.

**Comment by TheOneRing** [comment]
Ah makes sense, as there is no need for a.tar.7z I never ran in such a case.

**Comment by joesixpack** [comment]
> Oh,I see what you mean.
> BUT p7zip is a Linux version of 7zip. Therefore, its behavior is similar to 7zip.
> If 7zip is not supported, p7zip is not supported too. Sorry about that.
> But you can open issue at [7zip forum](https://sourceforge.net/p/sevenzip/discussion/45797/).

Well rather than trying to get this changed upstream, can you get the newer compressors to work with the formats that -so does support?

**Comment by jinfeihan57** [comment]
Actually no. I can't add new compressor to  xz, gzip, bzip2 and tar. Each format have a standard specification, It specifies which compression methods can be used. 
Can you tell me which new compressor you want?

**Comment by joesixpack** [comment]
I guess it doesn't matter at this point, but it was flmza2, zstd and brotli...  and hopefully the later would also be multi-threaded within the p7zip framework.  I will just use pzstd as flmza2 is still horribly slow.

**Comment by jinfeihan57** [comment]
Check the [benchmark](https://github.com/jinfeihan57/p7zip#benchmark).
Please use the latest master branch.
