### ISSUE TITLE
Where are the macos binary? Needed for Node JS wrapper of 7z

### ISSUE THREAD

**Issue by techno-express** [jinfeihan57/p7zip#105]
I have Node JS project [node-7z-archive](https://www.npmjs.com/package/node-7z-archive) that currently pulls **7zip** off **7-zip.org**, [sourceforge](https://sourceforge.net/projects/p7zip), and [rudix-mac ](https://rudix.org/). Extracts with [unar](https://theunarchiver.com/command-line) and place binaries within local node js package structure.

The project was using only standalone `7za`, just which to full `7z` and find there are issues with Linux & Mac OS versions when using full version only. Now it either does not see `7z.so` and looking for `7z.dll` instead on MacOS, or errors out with unexpected '(' on Linux.

Do you plan on releasing any Mac OS binary? 
It would be nice to use a more current and maintained release for these platforms.

**Comment by jinfeihan57** [comment]
I don't have a Mac right now. Maybe I'll do it later.
Can you Build binary by youself?
 make 7za && make7z
The build result is stored in the bin directory.

**Comment by techno-express** [comment]
I see you have GitHub Actions building for Mac and Linux. 
I thought you might have it scripted to copy binaries out.

Building myself would change my main focus. In pulling in what's already available that's being maintained, stuff i am not ready to maintain myself. Which i would have already started by now.

I guess you don't really have plans on seeing the project here move along too fast. 

I didn't really what my Node Js project to start pulling directly from ***.deb** and ***.rpm** binary repo's, since those versions are not any higher. But those should not have the errors i am seeing when using the **full 7z** from these other sources i have been using.
