### ISSUE TITLE
can not 7z x ISO file

### ISSUE THREAD

**Issue by StormRat** [jinfeihan57/p7zip#113]
huawei@0584c8621b15 /opt/buildtools/p7zip-17.02/bin]$7za -x /home/huawei/CentOS-7-x86_64-DVD-1804.iso 

Command Line Error:
Too short switch:
-x
[huawei@0584c8621b15 /opt/buildtools/p7zip-17.02/bin]$7za x /home/huawei/CentOS-7-x86_64-DVD-1804.iso 

7-Zip (a) [64] 17.02 : Copyright (c) 1999-2020 Igor Pavlov : 2017-08-28
p7zip Version 17.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,16 CPUs x64)

Scanning the drive for archives:
1 file, 4470079488 bytes (4263 MiB)

Extracting archive: /home/huawei/CentOS-7-x86_64-DVD-1804.iso
ERROR: /home/huawei/CentOS-7-x86_64-DVD-1804.iso
Can not open the file as archive

    
Can't open as archive: 1
Files: 0
Size:       0
Compressed: 0

\\\\\

[huawei@0584c8621b15 /home/huawei]$7za x SLE-12-SP5-Server-DVD-x86_64-GM-DVD1.iso 

7-Zip (a) [64] 17.02 : Copyright (c) 1999-2020 Igor Pavlov : 2017-08-28
p7zip Version 17.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,16 CPUs x64)

Scanning the drive for archives:
1 file, 4098883584 bytes (3909 MiB)

Extracting archive: SLE-12-SP5-Server-DVD-x86_64-GM-DVD1.iso
ERROR: SLE-12-SP5-Server-DVD-x86_64-GM-DVD1.iso
Can not open the file as archive

    
Can't open as archive: 1
Files: 0
Size:       0
Compressed: 0

**Comment by jinfeihan57** [comment]
Try 7z NOT 7za.
