### ISSUE TITLE
no install target provided in CMAKE build system

### ISSUE THREAD

**Issue by leleliu008** [jinfeihan57/p7zip#116]
I find no install target provided in `CMakeLists.txt`. It seems that no reasons motioned in docs, dos there exist some particular reasons?

I myself add following instructions to `CMakeLists.txt`:
```
install(PROGRAMS ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/7z_ ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/7za ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/7zr DESTINATION bin)
```

**Comment by jinfeihan57** [comment]
我认为p7zip最好由，用户自己配置环境变量的方式安装。因为7z(makefile) 或者7z_(cmake),依赖于Codecs 和 7z.so.并且7z_的安装还需要软链接为7z才好。与其我这里设置，不如用户自己或者其他包管理器来处理。

**Comment by leleliu008** [comment]
@jinfeihan57 明白了，谢谢您
