### ISSUE TITLE
Precompiled macOS binaries do not work under Sierra

### ISSUE THREAD

**Issue by MaxPower85** [jinfeihan57/p7zip#120]
The precompiled binaries do not work under Sierra

It is showing an error "dyld: Symbol not found: ____chkstk_darwin"

When you compile on Sierra, it does not show such an error

**Comment by techno-express** [comment]
The Github Actions build process is on macOS Catalina 10.15, or Bug Sur 11.0. There is not much that can be done about that.

**Comment by jinfeihan57** [comment]
@techno-express 
Can we add some system information to the package name?

**Comment by techno-express** [comment]
It seems info will need to be hard included, using another github action script for reading environment only shows `Darwin` for macOS as here: https://github.com/techno-express/p7zip/releases/tag/17.03.1

**Comment by jinfeihan57** [comment]
@techno-express 
Can we get the version number drawn in the picture?
![未命名1615551727](https://user-images.githubusercontent.com/38484902/110939903-0d24f100-8371-11eb-9c3a-28b9e948e43f.png)

**Comment by techno-express** [comment]
Done, I forked and created the github action script, added the option, and should be working like listed here: https://github.com/techno-express/p7zip/releases/tag/17.03.2
