### ISSUE TITLE
can you add a quiet mode to 7z?

### ISSUE THREAD

**Issue by Rimits** [jinfeihan57/p7zip#131]
I have a folder and many archives in it to test/extract.
```unzip -qqt "*.zip"``` can test multiple files directly and print out only warnings/errors, but it can only process zip files.
A for loop is needed to test multiple files using 7z ```for i in ./*zip ./*rar ./*z ;do 7z t $i;done```, but too many outputs flood into the terminal, and it's impossible to check for warnings/errors if there are too many archives.
can you add a quiet mode/option/switch to 7z similar to ```unzip -q``` or ```unrar -idq``` ?
or even better make ```7z``` able to process multiple files?

**Comment by tansy** [comment]
Maybe you can do that as pull request. It could be alias to existing `-bs{o|e|p}{0|1|2}` switch ([bs.html](https://sevenzip.osdn.jp/chm/cmdline/switches/bs.htm)).

For example `-q` would turn off progress (`-bsp0`), and `-qq` would also turn off standard output messages (`-bsp0 -bso0`), and `-qqq` would turn off all messages including error ones (`-bsp0 -bso0 -bse0`).

**Comment by jinfeihan57** [comment]
I think your problem can be solved using shell scripts.
sure()
{
  eval $*
  if [ "$?" != "0" ]
  then
    echo "ERROR during : $*"
    echo "ERROR during : $*" > last_error
    exit 1
  fi
}
for i in ./*zip ./*rar ./*z ;do 
    sure() 7z t $i >> result.txt
done

**Comment by Rimits** [comment]
Thanks，now I'm using the ```-bso0 -bsp0``` switch, and the results looks good.

```
~/Desktop$ for i in ./*zip ./*rar ./*z ;do 7z -bso0 -bsp0 t $i|| echo -e "ᛏᛏᛏ Errors in $i \n";done

ERROR: Data Error : astcenc.exe
ERROR: CRC Failed : PVRTexLib.dll
ᛏᛏᛏ Errors in ./UnityStudio.x64.v0.9.0.zip 


ERRORS:
Headers Error

ERROR: CRC Failed : 世界が終るまでは･･･ - WANDS.flac
ᛏᛏᛏ Errors in ./WAND.rar 

ERROR: CRC Failed : p95v303b6.linux64.tar
ᛏᛏᛏ Errors in ./p95v303b6.linux64.tar.gz 
```
