### ISSUE TITLE
xxhash - move to hashers

### ISSUE THREAD

**Issue by tansy** [jinfeihan57/p7zip#132]
If I can suggest one thing - xxhash should be in hashers not in zstd and it should not depend on it, which it does.
Zstd is not only codec using it (also lz4, and it was first, lizard, and fast-lzma2 and go one knows what else) and there is no reason do make it dependent on it.

**Comment by jinfeihan57** [comment]
Yes, I understand what you mean, but zstd is the first compression algorithm that added. Therefore, the source code of xxhash is kept in the zstd directory. So let's leave it there. :-)
