### ISSUE TITLE
Null-Pointer Dereference In NArchive::N7z::CInArchive::ReadUInt64DefVector

### ISSUE THREAD

**Issue by treebacker** [jinfeihan57/p7zip#133]
In `NArchive::N7z::CInArchive::ReadUInt64DefVector`, there is a null pointer dereference from ` NArchive::N7z::CInArchive::ReadHeader`.

In source code `p7zip/CPP/7zip/Archive/7z/7zIn.cpp`, below code:

```
void CInArchive::ReadUInt64DefVector(const CObjectVector<CByteBuffer> &dataVector,
    CUInt64DefVector &v, unsigned numItems)
{
  ReadBoolVector2(numItems, v.Defs);

  CStreamSwitch streamSwitch;
  streamSwitch.Set(this, &dataVector);
  
  v.Vals.ClearAndSetSize(numItems);
  UInt64 *p = &v.Vals[0];		
  const bool *defs = &v.Defs[0];	

  for (unsigned i = 0; i < numItems; i++)
  {
    UInt64 t = 0;
    if (defs[i])
      t = ReadUInt64();
    p[i] = t;			// p May be NULL
  }
}
```
With crafted 7z file,`p` may be Null.
In Command line:
![bug3_cmd](https://user-images.githubusercontent.com/44844446/113538249-56353180-960d-11eb-950c-34d89d62c530.png)
In gdb:
![bug3](https://user-images.githubusercontent.com/44844446/113538260-5e8d6c80-960d-11eb-8eb7-38caf1045a11.png)

The crafted 7z file (only ends wth ".zip"):

[bug3.zip](https://github.com/jinfeihan57/p7zip/files/6256358/bug3.zip)

**Comment by jinfeihan57** [comment]
I am Using ubuntu 18.04.
![捕获](https://user-images.githubusercontent.com/38484902/117319950-5d768600-aebe-11eb-8ed0-634aa5b35050.PNG)

**Comment by jinfeihan57** [comment]
fixed by @yangbonis 
check this[ PR](https://github.com/jinfeihan57/p7zip/pull/139).
