### ISSUE TITLE
Null Pointer Dereference In CDatabase::LoadCatalog.

### ISSUE THREAD

**Issue by treebacker** [jinfeihan57/p7zip#134]
`Null Pointer Dereference` In CDatabase::LoadCatalog.
In source code `CPP/7zip/Archive/HfsHandler.cpp`,
As below code shows:

```
struct CRef
{
  unsigned ItemIndex;
  int AttrIndex;
  int Parent;
  bool IsResource;

  bool IsAltStream() const { return IsResource || AttrIndex >= 0; }
  CRef(): AttrIndex(-1), Parent(-1), IsResource(false)  {}		// CRef Maybe Null
};


 void ClearAndReserve(unsigned newCapacity)
  {
    Clear();
    if (newCapacity > _capacity)
    {
      delete []_items;
      _items = NULL;
      _capacity = 0;
      MY_ARRAY_NEW(_items, T, newCapacity)
      // _items = new T[newCapacity];
      _capacity = newCapacity;
    }
  }


HRESULT CDatabase::LoadCatalog(const CFork &fork, const CObjectVector<CIdExtents> *overflowExtentsArray, IInStream *inStream, IArchiveOpenCallback *progress)
{
  unsigned reserveSize = (unsigned)(Header.NumFolders + 1 + Header.NumFiles);
  Items.ClearAndReserve(reserveSize);
  Refs.ClearAndReserve(reserveSize);		// Refs May be null
.....
}
```

Refs may be Null with crafted 7z file.

In command line:
![bug4_cmd](https://user-images.githubusercontent.com/44844446/113538569-22a6d700-960e-11eb-9e76-ee49a62ba245.png)

In gdb:
![bug4_gdb](https://user-images.githubusercontent.com/44844446/113538575-25093100-960e-11eb-8a83-1313b086c5dc.png)

Crafted 7z file:
[bug4.zip](https://github.com/jinfeihan57/p7zip/files/6256389/bug4.zip)

**Comment by jinfeihan57** [comment]
Can you test it on p7zip 16.02?

**Comment by treebacker** [comment]
Where i can download?

**Comment by treebacker** [comment]
The problem occurs in 16.02 too.
![bug4_](https://user-images.githubusercontent.com/44844446/113573567-ffe7e300-964c-11eb-92db-f56bda7a3ca0.png)

**Comment by jinfeihan57** [comment]
fixed by @yangbonis 
check this[ PR](https://github.com/jinfeihan57/p7zip/pull/139).
