### ISSUE TITLE
CMake 3.19.x throws deprecation warning

### ISSUE THREAD

**Issue by samoht0** [jinfeihan57/p7zip#135]
This goes for all CMakeLists.txt, due to defined version requirement of 2.6 and 2.8.
```
CMake Deprecation Warning at 7za/CMakeLists.txt:4 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.
```
Will probably break compilation with cmake 3.20.x, I guess. 
Setting minimum to 2.8.12 "cmake_minimum_required(VERSION 2.8.12)" and so dropping compatibly mode < 2.8.12 works without warning and builds fine. So seems to be an easy fix.

**Comment by jinfeihan57** [comment]
update [cmake version](https://github.com/jinfeihan57/p7zip/commit/91d7324ff508f28dcb5cb47777fb37b26272aa5d).
