### ISSUE TITLE
Build binary 7zip_21.02 again

### ISSUE THREAD

**Issue by teoberi** [jinfeihan57/p7zip#144]
7zip_21.02 with all commits
`cd p7zip/CPP/7zip/Bundles/Alone2 && make -f makefile.gcc`
> g++      -O2 -c -Wno-maybe-uninitialized -Wall -Werror -Wextra  -DNDEBUG -D_REENTRANT -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -fPIC   -o _o/Lz5Decoder.o  ../../Compress/Lz5Decoder.cpp
../../Compress/Lz5Decoder.cpp: In member function ‘virtual LONG NCompress::NLZ5::CDecoder::SetDecoderProperties2(const Byte*, UInt32)’:
../../Compress/Lz5Decoder.cpp:92:30: error: ‘void* memcpy(void*, const void*, size_t)’ writing to an object of a non-trivial type ‘struct NCompress::NLZ5::DProps’ leaves 2 bytes unchanged [-Werror=class-memaccess]
   92 |     memcpy(&_props, pProps, 3);
      |                              ^
In file included from ../../Compress/Lz5Decoder.cpp:4:
../../Compress/Lz5Decoder.h:34:12: note: ‘struct NCompress::NLZ5::DProps’ declared here
   34 |     struct DProps
      |            ^~~~~~
cc1plus: all warnings being treated as errors
make: *** [../../7zip_gcc.mak:1276: _o/Lz5Decoder.o] Error 1

**Comment by jinfeihan57** [comment]
I pushed a [commit](https://github.com/jinfeihan57/p7zip/commit/3e0e00c9dea697095a07e3ec8fcb9e12b9f225a7). Please try again.

**Comment by teoberi** [comment]
Fixed!
