### ISSUE TITLE
Fatal stat error when scanning directories with read but no execute permission

### ISSUE THREAD

**Issue by Hintro** [jinfeihan57/p7zip#146]
Whenever 7z scans a directory with r but no x permission,  it immediately terminates and no archive is made. By contrast, the standard zip and tar utilities archive an empty directory in this case, which I think is much more appropriate. Can you please make it behave like zip/tar either by default or by a switch like tar's --ignore-failed-read?

Thanks!

**Comment by jinfeihan57** [comment]
Can you try branch 7zip_21.02 ? That is the latest version.
p7zip should be used the same as 7zip, so please contact Igor Pavlov for new usage.
