### ISSUE TITLE
7zip_21.02 build issues

### ISSUE THREAD

**Issue by Hintro** [jinfeihan57/p7zip#148]
@jinfeihan57 Thanks for pointing me to 21.02, it does seem to behave more like zip/tar with permissions. However, I used 7zip's official Linux binaries because I was not able to build from branch 7zip_21.02. I'm using CentOS 7 and with gcc 7.40 and got these errors:
```
-- CMAKE_INSTALL_PREFIX: /usr/local
-- CMAKE_INSTALL_LIBDIR: lib64
-- ZSTD_LEGACY_SUPPORT not defined!
-- ZSTD_MULTITHREAD_SUPPORT is enabled
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
CMake Error at /usr/share/cmake/Modules/WriteBasicConfigVersionFile.cmake:39 (message):
  No VERSION specified for WRITE_BASIC_CONFIG_VERSION_FILE()
Call Stack (most recent call first):
  /usr/share/cmake/Modules/CMakePackageConfigHelpers.cmake:152 (write_basic_config_version_file)
  CMakeLists.txt:176 (write_basic_package_version_file)


-- Configuring incomplete, errors occurred!
See also "../../p7zip/CPP/7zip/Bundles/Alone2/zstd_build/CMakeFiles/CMakeOutput.log".
See also "../../p7zip/CPP/7zip/Bundles/Alone2/zstd_build/CMakeFiles/CMakeError.log".
make[1]: Entering directory `../../p7zip/CPP/7zip/Bundles/Alone2/zstd_build'
make[1]: *** No targets specified and no makefile found.  Stop.
make[1]: Leaving directory `../../p7zip/CPP/7zip/Bundles/Alone2/zstd_build'
cp: cannot stat 'zstd_build/lib/libzstd.a': No such file or directory
make: *** [_o/libzstd.a] Error 1
```

I also tried gcc 8.30, 9.30, 10.20 which failed a lot faster with these errors:
```
../gcc/8.3.0/install/bin/gcc      -O2 -c -Wno-maybe-uninitialized -Wall -Werror -Wextra  -DNDEBUG -D_REENTRANT -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -fPIC  -o _o/Aes.o ../../../../C/Aes.c
../gcc/8.3.0/install/bin/gcc      -O2 -c -Wno-maybe-uninitialized -Wall -Werror -Wextra  -DNDEBUG -D_REENTRANT -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -fPIC  -o _o/AesOpt.o ../../../../C/AesOpt.c
../cc2PTRQg.s: Assembler messages:
../cc2PTRQg.s:383: Error: operand type mismatch for `vaesdec'
../cc2PTRQg.s:384: Error: operand type mismatch for `vaesdec'
```

**Comment by teoberi** [comment]
I was able to build from branch 7zip_21.02
`cd p7zip/CPP/7zip/Bundles/Alone2 && make -f makefile.gcc`

> 7-Zip (z) 21.02 alpha (x64) : Copyright (c) 1999-2021 Igor Pavlov : 2021-05-06
 compiler: 10.3.0 GCC 10.3.0 64-bit locale=en_US.UTF-8 UTF8=+ use-UTF8=+ wchar_t=32-bit Files=64-bit Threads:4, Intel(R) Core(TM) i5-xxxx CPU @ x.xxGHz (xxxxx),AES

Could you post exactly the commands used for build binary?
Would you somehow use the -j option for make?
> -j [N], --jobs[=N]          Allow N jobs at once; infinite jobs with no arg.

I tried it in the case of 7zip_21.02 but also for p7zip and errors appear.

**Comment by Hintro** [comment]
I also used 
```
cd p7zip/CPP/7zip/Bundles/Alone2 && make -f makefile.gcc
```
copied from the branch's instructions, so I really don't know what went wrong here. Could it be that I need the zstd library installed to make it work?

**Comment by teoberi** [comment]
I have already installed the zstd package, you can try!

**Comment by tansy** [comment]
P7zip and 7zip are not the same thing. You should ask o in designated [thread](https://sourceforge.net/p/sevenzip/discussion/45797/thread/cec5e63147/) on sevenzip forum.

What is apparent here is that:
1. remove `-Werror` to compile files with warnings.
2. Zstd is not part of 7zip. You can find it [here](https://github.com/mcmilk/7-Zip-zstd).

**Comment by teoberi** [comment]
> P7zip and 7zip are not the same thing. You should ask o in designated [thread](https://sourceforge.net/p/sevenzip/discussion/45797/thread/cec5e63147/) on sevenzip forum.
> 
> What is apparent here is that:
> 
> 1. remove `-Werror` to compile files with warnings.
> 2. Zstd is not part of 7zip. You can find it [here](https://github.com/mcmilk/7-Zip-zstd).

Hintro say:
> However, I used 7zip's official Linux binaries because I was not able to build from branch 7zip_21.02.

Refers to: https://github.com/jinfeihan57/p7zip/tree/7zip_21.02

**Comment by tansy** [comment]
I tried it as well, and as said, I had to, I.a., remove `-Werror` and use assembler recommended by author, namely [asmc](https://github.com/nidud/asmc).

**Comment by teoberi** [comment]
You checked the two log files in the error message?
> See also "../../p7zip/CPP/7zip/Bundles/Alone2/zstd_build/CMakeFiles/CMakeOutput.log".
> See also "../../p7zip/CPP/7zip/Bundles/Alone2/zstd_build/CMakeFiles/CMakeError.log".

What version of cmake did you install? Is it updated?
https://gitlab.cern.ch/hepmc/HepMC3/-/issues/31 -> Issue 2
[CMake on Linux CentOS 7, how to force the system to use cmake3?](https://stackoverflow.com/questions/48831131/cmake-on-linux-centos-7-how-to-force-the-system-to-use-cmake3)

**Comment by Hintro** [comment]
Thanks! Turns out my cmake was too old. I did try using a newer cmake earlier by adding it to PATH but accidentally switched terminal window so it didn't make any effect lol.

Now this might be a dumb question: I used
```
cd CPP/7zip/Bundles/Alone2
make -j -f ../../cmpl_gcc_x64.mak
```
from Igor, and the building seemed to finish correctly, but I can't find the resulting 7zz binary...

**Comment by teoberi** [comment]
/p7zip/CPP/7zip/Bundles/Alone2/_o/7zz

**Comment by Hintro** [comment]
I did install asmc, and I found there were actually some errors:
```
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info
-- The CXX compiler identification is GNU 10.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: /share/pkg.7/gcc/10.2.0/install/bin/gcc
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: /share/pkg.7/gcc/10.2.0/install/bin/gcc - broken
-- Check for working C compiler: /share/pkg.7/gcc/10.2.0/install/bin/gcc
CMake Error at /share/pkg.7/cmake/3.19.4/install/share/cmake-3.19/Modules/CMakeTestCCompiler.cmake:66 (message):
  The C compiler

    "/share/pkg.7/gcc/10.2.0/install/bin/gcc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /usr4/cs501/jyliu/utils/p7zip/CPP/7zip/Bundles/Alone2/brotli_build/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/gmake cmTC_09b87/fast && gmake[1]: Entering directory `/usr4/cs501/jyliu/utils/p7zip/CPP/7zip/Bundles/Alone2/brotli_build/CMakeFiles/CMakeTmp'
    gmake[1]: *** No rule to make target `cmTC_09b87/fast'.  Stop.
    gmake[1]: Leaving directory `/usr4/cs501/jyliu/utils/p7zip/CPP/7zip/Bundles/Alone2/brotli_build/CMakeFiles/CMakeTmp'
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:7 (project)


-- Configuring incomplete, errors occurred!

See also "../p7zip/CPP/7zip/Bundles/Alone2/brotli_build/CMakeFiles/CMakeOutput.log".
See also "../p7zip/CPP/7zip/Bundles/Alone2/brotli_build/CMakeFiles/CMakeError.log".
```

**Comment by Hintro** [comment]
I did install asmc, and I found there were actually some errors:
```
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info
-- The CXX compiler identification is GNU 10.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: /share/pkg.7/gcc/10.2.0/install/bin/gcc
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: /share/pkg.7/gcc/10.2.0/install/bin/gcc - broken
-- Check for working C compiler: /share/pkg.7/gcc/10.2.0/install/bin/gcc
CMake Error at /share/pkg.7/cmake/3.19.4/install/share/cmake-3.19/Modules/CMakeTestCCompiler.cmake:66 (message):
  The C compiler

    "/share/pkg.7/gcc/10.2.0/install/bin/gcc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /p7zip/CPP/7zip/Bundles/Alone2/brotli_build/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/gmake cmTC_09b87/fast && gmake[1]: Entering directory `../p7zip/CPP/7zip/Bundles/Alone2/brotli_build/CMakeFiles/CMakeTmp'
    gmake[1]: *** No rule to make target `cmTC_09b87/fast'.  Stop.
    gmake[1]: Leaving directory `/usr4/cs501/jyliu/utils/p7zip/CPP/7zip/Bundles/Alone2/brotli_build/CMakeFiles/CMakeTmp'
    
    

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:7 (project)


-- Configuring incomplete, errors occurred!

See also "../p7zip/CPP/7zip/Bundles/Alone2/brotli_build/CMakeFiles/CMakeOutput.log".
See also "../p7zip/CPP/7zip/Bundles/Alone2/brotli_build/CMakeFiles/CMakeError.log".
```

**Comment by teoberi** [comment]
So you didn't get the 7zz binary in the path /p7zip/CPP/7zip/Bundles/Alone2/ _o/
Try compilation without asmc with the command:
`cd p7zip/CPP/7zip/Bundles/Alone2 && make -f makefile.gcc`

**Comment by Hintro** [comment]
Now I'm back to the AES assembly error, even without -Werror:
```
/share/pkg.7/gcc/10.2.0/install/bin/gcc      -O2 -c -Wno-maybe-uninitialized -Wall -Wextra  -DNDEBUG -D_REENTRANT -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -fPIC  -o _o/Aes.o ../../../../C/Aes.c
/share/pkg.7/gcc/10.2.0/install/bin/gcc      -O2 -c -Wno-maybe-uninitialized -Wall -Wextra  -DNDEBUG -D_REENTRANT -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -fPIC  -o _o/AesOpt.o ../../../../C/AesOpt.c
../cc8o1Xd0.s: Assembler messages:
../cc8o1Xd0.s:421: Error: operand type mismatch for `vaesdec'
../cc8o1Xd0.s:422: Error: operand type mismatch for `vaesdec'
```

**Comment by teoberi** [comment]
> Check for working C compiler: /share/pkg.7/gcc/10.2.0/install/bin/gcc - broken

Run the commands:
`gcc --version`
`g++ --version`
Maybe you should reinstall gcc?

**Comment by Hintro** [comment]
I'd like to, but I can't since I'm on a shared cluster where I don't have root privileges. Quite a few gcc versions are available for use, but I can't install them myself.

**Comment by teoberi** [comment]
With pleasure!
So you compiled in the end without asmc.
I will try compiling with JWasm instead of asmc.
https://github.com/jinfeihan57/p7zip/blob/7zip_21.02/CPP/7zip/7zip_gcc.mak

> MY_ASM = jwasm

**Comment by Hintro** [comment]
Thanks! I'll definitely give it a try when I have time.
