### ISSUE TITLE
Please update branch 7zip_21.02

### ISSUE THREAD

**Issue by pashamcr** [jinfeihan57/p7zip#156]
Please update branch 7zip_21.02 as 7-Zip 21.03 beta is out https://sourceforge.net/p/sevenzip/discussion/45797/thread/9f5b067368/

**Comment by teoberi** [comment]
The same request, major modern codecs such as Brotli, Fast LZMA2, LZ4, LZ5, Lizard and Zstd make the difference from the original source code of Igor Pavlov.

**Comment by jinfeihan57** [comment]
Sorry, I have been very busy in recent months.  Did not pay attention to the github community in time.  I have made a branch of p7zip21 before (in May). I haven't checked the latest 7zip code to see if there are major changes.  If there is not much change.  I will release it as the master branch as soon as possible.  Everyone is welcome to comment on the p7zip21.0 branch.

**Comment by teoberi** [comment]
I have been using the 7zip_21.02 branch since May on my servers without any problems. Agree with the idea of releasing 7zip_21.03 with major modern codecs as the master branch. I will compile and test it as soon as it appears.
I'm glad you're OK and you were just busy.

**Comment by teoberi** [comment]
`diff -qr 7z2102/ 7z2103/`

> Files 7z2102/Asm/x86/7zAsm.asm and 7z2103/Asm/x86/7zAsm.asm differ
Only in 7z2103/Asm/x86: LzFindOpt.asm
Files 7z2102/C/7zTypes.h and 7z2103/C/7zTypes.h differ
Files 7z2102/C/7zVersion.h and 7z2103/C/7zVersion.h differ
Files 7z2102/C/Aes.c and 7z2103/C/Aes.c differ
Files 7z2102/C/Alloc.c and 7z2103/C/Alloc.c differ
Files 7z2102/C/Alloc.h and 7z2103/C/Alloc.h differ
Files 7z2102/C/CpuArch.c and 7z2103/C/CpuArch.c differ
Files 7z2102/C/CpuArch.h and 7z2103/C/CpuArch.h differ
Files 7z2102/C/LzFind.c and 7z2103/C/LzFind.c differ
Files 7z2102/C/LzFind.h and 7z2103/C/LzFind.h differ
Files 7z2102/C/LzFindMt.c and 7z2103/C/LzFindMt.c differ
Files 7z2102/C/LzFindMt.h and 7z2103/C/LzFindMt.h differ
Only in 7z2103/C: LzFindOpt.c
Files 7z2102/C/LzmaEnc.c and 7z2103/C/LzmaEnc.c differ
Files 7z2102/C/MtCoder.c and 7z2103/C/MtCoder.c differ
Files 7z2102/C/Sha1.c and 7z2103/C/Sha1.c differ
Files 7z2102/C/Threads.c and 7z2103/C/Threads.c differ
Files 7z2102/C/Threads.h and 7z2103/C/Threads.h differ
Files 7z2102/C/Util/LzmaLib/LzmaLib.dsp and 7z2103/C/Util/LzmaLib/LzmaLib.dsp differ
Files 7z2102/C/Util/LzmaLib/makefile and 7z2103/C/Util/LzmaLib/makefile differ
Files 7z2102/C/var_clang_x64.mak and 7z2103/C/var_clang_x64.mak differ
Files 7z2102/C/var_clang_x86.mak and 7z2103/C/var_clang_x86.mak differ
Files 7z2102/C/var_gcc_x86.mak and 7z2103/C/var_gcc_x86.mak differ
Files 7z2102/C/warn_gcc.mak and 7z2103/C/warn_gcc.mak differ
Files 7z2102/CPP/7zip/7zip_gcc.mak and 7z2103/CPP/7zip/7zip_gcc.mak differ
Files 7z2102/CPP/7zip/Archive/7z/7zHandlerOut.cpp and 7z2103/CPP/7zip/Archive/7z/7zHandlerOut.cpp differ
Files 7z2102/CPP/7zip/Archive/Zip/ZipHeader.h and 7z2103/CPP/7zip/Archive/Zip/ZipHeader.h differ
Files 7z2102/CPP/7zip/Archive/Zip/ZipItem.cpp and 7z2103/CPP/7zip/Archive/Zip/ZipItem.cpp differ
Files 7z2102/CPP/7zip/Bundles/Alone/Alone.dsp and 7z2103/CPP/7zip/Bundles/Alone/Alone.dsp differ
Files 7z2102/CPP/7zip/Bundles/Alone/makefile and 7z2103/CPP/7zip/Bundles/Alone/makefile differ
Files 7z2102/CPP/7zip/Bundles/Alone/makefile.gcc and 7z2103/CPP/7zip/Bundles/Alone/makefile.gcc differ
Files 7z2102/CPP/7zip/Bundles/Alone7z/Alone.dsp and 7z2103/CPP/7zip/Bundles/Alone7z/Alone.dsp differ
Files 7z2102/CPP/7zip/Bundles/Alone7z/makefile and 7z2103/CPP/7zip/Bundles/Alone7z/makefile differ
Files 7z2102/CPP/7zip/Bundles/Alone7z/makefile.gcc and 7z2103/CPP/7zip/Bundles/Alone7z/makefile.gcc differ
Files 7z2102/CPP/7zip/Bundles/Fm/FM.dsp and 7z2103/CPP/7zip/Bundles/Fm/FM.dsp differ
Files 7z2102/CPP/7zip/Bundles/Format7z/makefile and 7z2103/CPP/7zip/Bundles/Format7z/makefile differ
Files 7z2102/CPP/7zip/Bundles/Format7zF/Arc.mak and 7z2103/CPP/7zip/Bundles/Format7zF/Arc.mak differ
Files 7z2102/CPP/7zip/Bundles/Format7zF/Arc_gcc.mak and 7z2103/CPP/7zip/Bundles/Format7zF/Arc_gcc.mak differ
Files 7z2102/CPP/7zip/Bundles/Format7zF/Format7z.dsp and 7z2103/CPP/7zip/Bundles/Format7zF/Format7z.dsp differ
Files 7z2102/CPP/7zip/Bundles/Format7zR/makefile and 7z2103/CPP/7zip/Bundles/Format7zR/makefile differ
Files 7z2102/CPP/7zip/Bundles/LzmaCon/LzmaCon.dsp and 7z2103/CPP/7zip/Bundles/LzmaCon/LzmaCon.dsp differ
Files 7z2102/CPP/7zip/Bundles/LzmaCon/makefile and 7z2103/CPP/7zip/Bundles/LzmaCon/makefile differ
Files 7z2102/CPP/7zip/Bundles/LzmaCon/makefile.gcc and 7z2103/CPP/7zip/Bundles/LzmaCon/makefile.gcc differ
Files 7z2102/CPP/7zip/Common/MemBlocks.cpp and 7z2103/CPP/7zip/Common/MemBlocks.cpp differ
Files 7z2102/CPP/7zip/Common/MethodProps.cpp and 7z2103/CPP/7zip/Common/MethodProps.cpp differ
Files 7z2102/CPP/7zip/Common/MethodProps.h and 7z2103/CPP/7zip/Common/MethodProps.h differ
Files 7z2102/CPP/7zip/Common/OffsetStream.cpp and 7z2103/CPP/7zip/Common/OffsetStream.cpp differ
Files 7z2102/CPP/7zip/Common/StreamBinder.cpp and 7z2103/CPP/7zip/Common/StreamBinder.cpp differ
Files 7z2102/CPP/7zip/Compress/DeflateDecoder.cpp and 7z2103/CPP/7zip/Compress/DeflateDecoder.cpp differ
Files 7z2102/CPP/7zip/Compress/DeflateEncoder.cpp and 7z2103/CPP/7zip/Compress/DeflateEncoder.cpp differ
Files 7z2102/CPP/7zip/Compress/LzmaEncoder.cpp and 7z2103/CPP/7zip/Compress/LzmaEncoder.cpp differ
Files 7z2102/CPP/7zip/Compress/PpmdEncoder.cpp and 7z2103/CPP/7zip/Compress/PpmdEncoder.cpp differ
Only in 7z2103/CPP/7zip: LzFindOpt.mak
Files 7z2102/CPP/7zip/UI/Common/ArchiveCommandLine.cpp and 7z2103/CPP/7zip/UI/Common/ArchiveCommandLine.cpp differ
Files 7z2102/CPP/7zip/UI/Common/ArchiveCommandLine.h and 7z2103/CPP/7zip/UI/Common/ArchiveCommandLine.h differ
Files 7z2102/CPP/7zip/UI/Common/Bench.cpp and 7z2103/CPP/7zip/UI/Common/Bench.cpp differ
Files 7z2102/CPP/7zip/UI/Common/Bench.h and 7z2103/CPP/7zip/UI/Common/Bench.h differ
Files 7z2102/CPP/7zip/UI/Common/CompressCall2.cpp and 7z2103/CPP/7zip/UI/Common/CompressCall2.cpp differ
Files 7z2102/CPP/7zip/UI/Console/Main.cpp and 7z2103/CPP/7zip/UI/Console/Main.cpp differ
Files 7z2102/CPP/7zip/UI/FileManager/AboutDialog.cpp and 7z2103/CPP/7zip/UI/FileManager/AboutDialog.cpp differ
Files 7z2102/CPP/7zip/UI/FileManager/ProgressDialog.cpp and 7z2103/CPP/7zip/UI/FileManager/ProgressDialog.cpp differ
Files 7z2102/CPP/7zip/UI/FileManager/ProgressDialog2.cpp and 7z2103/CPP/7zip/UI/FileManager/ProgressDialog2.cpp differ
Files 7z2102/CPP/7zip/UI/FileManager/ProgressDialog2.h and 7z2103/CPP/7zip/UI/FileManager/ProgressDialog2.h differ
Files 7z2102/CPP/7zip/UI/FileManager/ProgressDialog2Res.h and 7z2103/CPP/7zip/UI/FileManager/ProgressDialog2Res.h differ
Files 7z2102/CPP/7zip/UI/FileManager/ProgressDialog2a.rc and 7z2103/CPP/7zip/UI/FileManager/ProgressDialog2a.rc differ
Files 7z2102/CPP/7zip/UI/GUI/BenchmarkDialog.cpp and 7z2103/CPP/7zip/UI/GUI/BenchmarkDialog.cpp differ
Files 7z2102/CPP/7zip/UI/GUI/BenchmarkDialog.h and 7z2103/CPP/7zip/UI/GUI/BenchmarkDialog.h differ
Files 7z2102/CPP/7zip/UI/GUI/BenchmarkDialog.rc and 7z2103/CPP/7zip/UI/GUI/BenchmarkDialog.rc differ
Files 7z2102/CPP/7zip/UI/GUI/BenchmarkDialogRes.h and 7z2103/CPP/7zip/UI/GUI/BenchmarkDialogRes.h differ
Files 7z2102/CPP/7zip/UI/GUI/CompressDialog.cpp and 7z2103/CPP/7zip/UI/GUI/CompressDialog.cpp differ
Files 7z2102/CPP/7zip/UI/GUI/CompressDialog.h and 7z2103/CPP/7zip/UI/GUI/CompressDialog.h differ
Files 7z2102/CPP/7zip/UI/GUI/GUI.cpp and 7z2103/CPP/7zip/UI/GUI/GUI.cpp differ
Files 7z2102/CPP/7zip/UI/GUI/GUI.dsp and 7z2103/CPP/7zip/UI/GUI/GUI.dsp differ
Files 7z2102/CPP/7zip/UI/GUI/UpdateGUI.cpp and 7z2103/CPP/7zip/UI/GUI/UpdateGUI.cpp differ
Files 7z2102/CPP/7zip/warn_clang_mac.mak and 7z2103/CPP/7zip/warn_clang_mac.mak differ
Files 7z2102/CPP/7zip/warn_gcc.mak and 7z2103/CPP/7zip/warn_gcc.mak differ
Only in 7z2103/CPP/Common: LzFindPrepare.cpp
Files 7z2102/CPP/Common/MyBuffer2.h and 7z2103/CPP/Common/MyBuffer2.h differ
Files 7z2102/CPP/Windows/Control/Dialog.cpp and 7z2103/CPP/Windows/Control/Dialog.cpp differ
Files 7z2102/CPP/Windows/Control/Dialog.h and 7z2103/CPP/Windows/Control/Dialog.h differ
Files 7z2102/CPP/Windows/ErrorMsg.cpp and 7z2103/CPP/Windows/ErrorMsg.cpp differ
Files 7z2102/CPP/Windows/Registry.cpp and 7z2103/CPP/Windows/Registry.cpp differ
Files 7z2102/CPP/Windows/Synchronization.h and 7z2103/CPP/Windows/Synchronization.h differ
Files 7z2102/CPP/Windows/SystemInfo.cpp and 7z2103/CPP/Windows/SystemInfo.cpp differ
Files 7z2102/CPP/Windows/SystemInfo.h and 7z2103/CPP/Windows/SystemInfo.h differ
Files 7z2102/DOC/7zip.wxs and 7z2103/DOC/7zip.wxs differ
Files 7z2102/DOC/readme.txt and 7z2103/DOC/readme.txt differ

**Comment by teoberi** [comment]
It seems that there are some changes that take a while.

**Comment by teoberi** [comment]
We are already at 7-Zip 21.04 beta. Maybe the final version will be updated?

**Comment by pashamcr** [comment]
7z stable released https://sourceforge.net/projects/sevenzip/files/7-Zip/21.04/

**Comment by teoberi** [comment]
As already announced by @pashamcr (by mail) 7-Zip 21.04 is already available.
Good news after other bad things this week.

**Comment by teoberi** [comment]
7-zip 21.05 has been released but the sources have not been published yet.

**Comment by teoberi** [comment]
7-zip 21.06 has been released with sources code!
https://www.7-zip.org/download.html

**Comment by teoberi** [comment]
And [Zstandard v1.5.1](https://github.com/facebook/zstd/releases/tag/v1.5.1)

**Comment by teoberi** [comment]
7-zip 21.07 has been released with sources code!
https://www.7-zip.org/download.html

**Comment by jinfeihan57** [comment]
Working on [p7zip22.0](https://github.com/jinfeihan57/p7zip/tree/p7zip22.00).
