### ISSUE TITLE
AES broken with jwasm-family (jwasm, asmc, uasm) assemblers

### ISSUE THREAD

**Issue by ghost** [jinfeihan57/p7zip#174]
Please see [this upstream bug report](https://sourceforge.net/p/sevenzip/bugs/2338/) for more details.
A patch to workaround this issue can be found in [this comment](https://sourceforge.net/p/sevenzip/bugs/2338/?limit=25#8570).

**Comment by jinfeihan57** [comment]
p7zip is not compiled with assembly code, but thank you very much for your attention, I will still fix the error code in the new version.
