### ISSUE TITLE
New upstream release 7-Zip 22.01

### ISSUE THREAD

**Issue by antermin** [jinfeihan57/p7zip#177]
https://sourceforge.net/p/sevenzip/discussion/45797/thread/9c2d9061ce/?limit=25#b964
CC @cielavenir

**Comment by jinfeihan57** [comment]
It seems that the source code has not been officially released.

**Comment by cielavenir** [comment]
@jinfeihan57 

https://www.7-zip.org/download.html

```
Download 7-Zip 22.00 (2022-06-15):
[Download](https://www.7-zip.org/a/7z2200-src.7z)	.7z	any / Windows	7-Zip Source code
```

**Comment by cielavenir** [comment]
@jinfeihan57 by the way, could you make a hash which is the **exact unmodified** mirror of upstream 7-zip?

**Comment by jinfeihan57** [comment]
> @jinfeihan57 by the way, could you make a hash which is the **exact unmodified** mirror of upstream 7-zip?

Please provide a new issue for new requirements

**Comment by jinfeihan57** [comment]
> @jinfeihan57
> 
> https://www.7-zip.org/download.html
> 
> ```
> Download 7-Zip 22.00 (2022-06-15):
> [Download](https://www.7-zip.org/a/7z2200-src.7z)	.7z	any / Windows	7-Zip Source code
> ```
Thanks，I will do it as soon as possible.

**Comment by cielavenir** [comment]
hi https://github.com/cielavenir/p7zip/releases/tag/22.01.1

**Comment by jinfeihan57** [comment]
Working on [p7zip22.00](https://github.com/jinfeihan57/p7zip/tree/p7zip22.00).
