### ISSUE TITLE
In-place archive decryption

### ISSUE THREAD

**Issue by AstroSnail** [jinfeihan57/p7zip#189]
I have a question: is it possible to decrypt an encrypted 7z archive in-place, similarly to `zipcloak -d` for zip?

If not, are there alternative steps that achieve a similar effect? (preserve metadata, ideally also preserve compression and file order)

**Comment by jinfeihan57** [comment]
You can use a shell script to unpack and repack the xxx.7z file and add whatever you want.

**Comment by AstroSnail** [comment]
that shell script method risks losing metadata (i tested this and the file attributes were not preserved), and is extremely slow (and space-inefficient if done naively). it's not exactly what i'm asking for. i'd like a method that doesn't lose metadata, and ideally simply decrypts the compressed files instead of de- and re-compressing

**Comment by jinfeihan57** [comment]
Sorry, the 7z doesn't have [zipcloak](https://www.computerhope.com/unix/zipcloak.htm) feature.
