### ISSUE TITLE
Can't compile 7z.so, error in _o/bin directory

### ISSUE THREAD

**Issue by acdcjavier** [jinfeihan57/p7zip#197]
Hi

After to perform a make for compile 7z.so, I got this error:

```
~/p7zip/CPP/7zip/Bundles/Format7zF$ sudo make -f makefile.gcc install
mkdir -p /usr/local/bin
cp -drf _o/bin/* /usr/local/bin
cp: cannot stat '_o/bin/*': No such file or directory
make: *** [../../7zip_gcc.mak:1444: install] Error 1
```

After checking _o/bin/ folder, doesn't exist any file.

Can you help me to finish to compile?

**Comment by cielavenir** [comment]
You need to use the same makefile. If you used ../../cmpl_gcc.mak, need ../../cmpl_gcc.mak to install as well.

**Comment by jinfeihan57** [comment]
Please "make" first then "make install".
